/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 office.gltf --transform
Author: maxdragonn (https://sketchfab.com/maxdragon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-phone-4176a01b6d0b4d13ad165c0df278a6b5
Title: Office Phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3d/office-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 3.8, -0.4, -10]}>
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.phone_a_0.geometry} material={materials.phone_a} position={[0, 0, -0.3]} scale={0.3} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/office-transformed.glb')
