/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: maxdragonn (https://sketchfab.com/maxdragon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-phone-4176a01b6d0b4d13ad165c0df278a6b5
title: Office Phone
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        phone_a_0: THREE.Mesh;
    };
    materials: {
        phone_a: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF("/3d/office_phone.glb") as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    userData={{ name: "Sketchfab_model" }}
                >
                    <group name="Root" userData={{ name: "Root" }}>
                        <group
                            name="Lamp"
                            position={[4.07625, 1.00545, 5.90386]}
                            rotation={[-0.26819701, 0.60212023, 1.93149649]}
                            scale={[0.9999976, 0.99999583, 0.99999612]}
                            userData={{ name: "Lamp" }}
                        >
                            <group name="Lamp_1" userData={{ name: "Lamp" }} />
                        </group>
                        <group
                            name="phone_a"
                            position={[0, 0, -0.3]}
                            userData={{ name: "phone_a" }}
                        >
                            <mesh
                                name="phone_a_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.phone_a_0.geometry}
                                material={materials.phone_a}
                                userData={{ name: "phone_a_0" }}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/3d/office_phone.glb");
